//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentDesign
    {
        public string CD_ID { get; set; }
        public string CD_DocType { get; set; }
        public string CD_Name { get; set; }
        public Nullable<int> CD_isEnable { get; set; }
        public Nullable<int> CD_isVisiable { get; set; }
        public string CD_FiledName { get; set; }
        public string CD_Caption { get; set; }
        public string CD_CaptionEN { get; set; }
        public string CD_CaptionCN { get; set; }
        public Nullable<int> CD_Index { get; set; }
        public Nullable<int> CD_Width { get; set; }
    }
}
