//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter
    {
        public CostCenter()
        {
            this.WFNodeDetails = new HashSet<WFNodeDetail>();
            this.Users = new HashSet<User>();
            this.ExportItemApproverItems = new HashSet<ExportItemApproverItem>();
            this.ExportItemDetails = new HashSet<ExportItemDetail>();
            this.GAAdjustments = new HashSet<GAAdjustment>();
            this.WFDelegates = new HashSet<WFDelegate>();
        }
    
        public int CostCenterCode { get; set; }
        public int CompanyCode { get; set; }
        public string Remark { get; set; }
        public Nullable<short> Enabled { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual ICollection<WFNodeDetail> WFNodeDetails { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<ExportItemApproverItem> ExportItemApproverItems { get; set; }
        public virtual ICollection<ExportItemDetail> ExportItemDetails { get; set; }
        public virtual ICollection<GAAdjustment> GAAdjustments { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<WFDelegate> WFDelegates { get; set; }
    }
}
