//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPDocumentDetail
    {
        public string ItemID { get; set; }
        public string ERPDocumentsID { get; set; }
        public string FEPO { get; set; }
        public string MaterialName { get; set; }
        public string Spec { get; set; }
        public string ColorCode { get; set; }
        public string ColorName { get; set; }
        public string StockPosition { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public string Remark { get; set; }
        public string DeclarationDate { get; set; }
        public string DeclarationCode { get; set; }
        public string MinimumType { get; set; }
        public string MaterialCode { get; set; }
        public string AimFEPO { get; set; }
    
        public virtual ERPDocument ERPDocument { get; set; }
    }
}
