//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPDocument
    {
        public ERPDocument()
        {
            this.ERPDocumentDetails = new HashSet<ERPDocumentDetail>();
        }
    
        public string ID { get; set; }
        public string StockOutOrderID { get; set; }
        public string OrderCode { get; set; }
        public string OrderType { get; set; }
        public string LevelName { get; set; }
        public int Status { get; set; }
        public string CreateDate { get; set; }
        public int UserID { get; set; }
        public int Version { get; set; }
        public string DepartmentName { get; set; }
        public string WarehouseName { get; set; }
        public string InvoiceCode { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsUnexpected { get; set; }
        public string ReasonName { get; set; }
        public Nullable<int> TradeType { get; set; }
    
        public virtual ICollection<ERPDocumentDetail> ERPDocumentDetails { get; set; }
        public virtual User User { get; set; }
    }
}
