//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportItemChecking
    {
        public string ID { get; set; }
        public string ExportItemDetailID { get; set; }
        public string OperationType { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
    
        public virtual User User { get; set; }
        public virtual ExportItemDetail ExportItemDetail { get; set; }
        public virtual ExportItemDetail ExportItemDetail1 { get; set; }
    }
}
