//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportItem
    {
        public ExportItem()
        {
            this.ExportItem1 = new HashSet<ExportItem>();
            this.ExportItemDetails = new HashSet<ExportItemDetail>();
        }
    
        public string ID { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string Destination { get; set; }
        public string PersonalName { get; set; }
        public string ReasonID { get; set; }
        public string ReasonName { get; set; }
        public string Description { get; set; }
        public string ExportItemAdjustID { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public Nullable<int> UserProcessID { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string AttachmentLink { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual SADestination SADestination { get; set; }
        public virtual ICollection<ExportItem> ExportItem1 { get; set; }
        public virtual ExportItem ExportItem2 { get; set; }
        public virtual ICollection<ExportItemDetail> ExportItemDetails { get; set; }
    }
}
