//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportItemApproverItem
    {
        public string ID { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public int CostCenterCode { get; set; }
        public string ItemID { get; set; }
        public string ItemDetailID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
    
        public virtual CostCenter CostCenter { get; set; }
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
