//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportItemDetail
    {
        public ExportItemDetail()
        {
            this.ExportItemCheckings = new HashSet<ExportItemChecking>();
            this.ExportItemCheckings1 = new HashSet<ExportItemChecking>();
        }
    
        public string ID { get; set; }
        public string ExportItemID { get; set; }
        public Nullable<int> CostCenterCode { get; set; }
        public string ItemID { get; set; }
        public string ItemDetailID { get; set; }
        public string Specification { get; set; }
        public string Note { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public string UnitID { get; set; }
    
        public virtual CostCenter CostCenter { get; set; }
        public virtual ExportItem ExportItem { get; set; }
        public virtual ICollection<ExportItemChecking> ExportItemCheckings { get; set; }
        public virtual ICollection<ExportItemChecking> ExportItemCheckings1 { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual ItemDetail ItemDetail { get; set; }
    }
}
