//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAAdjustment
    {
        public string ID { get; set; }
        public Nullable<int> CostCenterCode { get; set; }
        public string ItemDetail { get; set; }
        public Nullable<decimal> AdjustQuantity { get; set; }
        public Nullable<decimal> AdjustAmount { get; set; }
        public System.DateTime Month { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Damged { get; set; }
    
        public virtual CostCenter CostCenter { get; set; }
    }
}
