//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAItem
    {
        public GAItem()
        {
            this.GAItemDetails = new HashSet<GAItemDetail>();
        }
    
        public string ID { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> IsUrgent { get; set; }
        public Nullable<decimal> EstimateAmount { get; set; }
        public string CurrencyID { get; set; }
        public string Description { get; set; }
        public string Reason { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string AttachmentLink { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string PRCode { get; set; }
        public string CMCKCode { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<GAItemDetail> GAItemDetails { get; set; }
    }
}
