//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwareRequirement
    {
        public HardwareRequirement()
        {
            this.HardwareRequirementDetails = new HashSet<HardwareRequirementDetail>();
            this.HardwareRequirementDetails1 = new HashSet<HardwareRequirementDetail>();
            this.HardwareRequirementDetails2 = new HashSet<HardwareRequirementDetail>();
        }
    
        public string ID { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> IsUrgent { get; set; }
        public Nullable<decimal> EstimatedAmount { get; set; }
        public string CurrencyID { get; set; }
        public string Description { get; set; }
        public string Reason { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string AttachmentLink { get; set; }
        public string ProcessedBy { get; set; }
        public Nullable<System.DateTime> CompleteEstimateDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<HardwareRequirementDetail> HardwareRequirementDetails { get; set; }
        public virtual ICollection<HardwareRequirementDetail> HardwareRequirementDetails1 { get; set; }
        public virtual ICollection<HardwareRequirementDetail> HardwareRequirementDetails2 { get; set; }
    }
}
