//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetail
    {
        public ItemDetail()
        {
            this.DeviceRegistrationDetails = new HashSet<DeviceRegistrationDetail>();
            this.DeviceRegistrationDetails1 = new HashSet<DeviceRegistrationDetail>();
            this.DeviceRegistrationDetails2 = new HashSet<DeviceRegistrationDetail>();
            this.ExportItemDetails = new HashSet<ExportItemDetail>();
            this.GAItemDetails = new HashSet<GAItemDetail>();
            this.ITInventories = new HashSet<ITInventory>();
            this.WHImportOrderDetails = new HashSet<WHImportOrderDetail>();
            this.HardwareRequirementDetails = new HashSet<HardwareRequirementDetail>();
            this.HardwareRequirementDetails1 = new HashSet<HardwareRequirementDetail>();
            this.HardwareRequirementDetails2 = new HashSet<HardwareRequirementDetail>();
            this.StockInEquipmentDetails = new HashSet<StockInEquipmentDetail>();
            this.StockInEquipmentDetails1 = new HashSet<StockInEquipmentDetail>();
            this.StockInEquipmentDetails2 = new HashSet<StockInEquipmentDetail>();
            this.StockOutEquipmentDetails = new HashSet<StockOutEquipmentDetail>();
            this.MNRequestMainDetails = new HashSet<MNRequestMainDetail>();
            this.MNStockEquipmentDetails = new HashSet<MNStockEquipmentDetail>();
            this.MNInventories = new HashSet<MNInventory>();
            this.MRBRoomEquipments = new HashSet<MRBRoomEquipment>();
        }
    
        public string ID { get; set; }
        public string ItemID { get; set; }
        public string ItemDetailName { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<DeviceRegistrationDetail> DeviceRegistrationDetails { get; set; }
        public virtual ICollection<DeviceRegistrationDetail> DeviceRegistrationDetails1 { get; set; }
        public virtual ICollection<DeviceRegistrationDetail> DeviceRegistrationDetails2 { get; set; }
        public virtual ICollection<ExportItemDetail> ExportItemDetails { get; set; }
        public virtual ICollection<GAItemDetail> GAItemDetails { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<ITInventory> ITInventories { get; set; }
        public virtual ICollection<WHImportOrderDetail> WHImportOrderDetails { get; set; }
        public virtual ICollection<HardwareRequirementDetail> HardwareRequirementDetails { get; set; }
        public virtual ICollection<HardwareRequirementDetail> HardwareRequirementDetails1 { get; set; }
        public virtual ICollection<HardwareRequirementDetail> HardwareRequirementDetails2 { get; set; }
        public virtual ICollection<StockInEquipmentDetail> StockInEquipmentDetails { get; set; }
        public virtual ICollection<StockInEquipmentDetail> StockInEquipmentDetails1 { get; set; }
        public virtual ICollection<StockInEquipmentDetail> StockInEquipmentDetails2 { get; set; }
        public virtual ICollection<StockOutEquipmentDetail> StockOutEquipmentDetails { get; set; }
        public virtual ICollection<MNRequestMainDetail> MNRequestMainDetails { get; set; }
        public virtual ICollection<MNStockEquipmentDetail> MNStockEquipmentDetails { get; set; }
        public virtual ICollection<MNInventory> MNInventories { get; set; }
        public virtual ICollection<MRBRoomEquipment> MRBRoomEquipments { get; set; }
    }
}
