//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITSAssetRecData
    {
        public ITSAssetRecData()
        {
            this.ITSAssetDetails = new HashSet<ITSAssetDetail>();
        }
    
        public string ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<ITSAssetDetail> ITSAssetDetails { get; set; }
    }
}
