//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogChangePass
    {
        public int LogID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> LogCreatePassDate { get; set; }
        public Nullable<System.DateTime> LogExpiredPassDate { get; set; }
        public string ChangePassLog { get; set; }
    
        public virtual User User { get; set; }
    }
}
