//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNStockEquipment
    {
        public MNStockEquipment()
        {
            this.MNStockEquipmentDetails = new HashSet<MNStockEquipmentDetail>();
        }
    
        public string ID { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string DocType { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string RequestMainID { get; set; }
        public Nullable<int> DeliveryFor { get; set; }
    
        public virtual MNRequestMain MNRequestMain { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<MNStockEquipmentDetail> MNStockEquipmentDetails { get; set; }
    }
}
