//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNStockEquipmentDetail
    {
        public string DetailID { get; set; }
        public string StockInEquipmentID { get; set; }
        public string ItemID { get; set; }
        public string ItemDetailID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string UnitID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReceiveUserID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ItemDetail ItemDetail { get; set; }
        public virtual MNStockEquipment MNStockEquipment { get; set; }
        public virtual User User { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
