//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRBRoomType
    {
        public MRBRoomType()
        {
            this.MRBRooms = new HashSet<MRBRoom>();
        }
    
        public int RoomTypeId { get; set; }
        public string RoomTypeName { get; set; }
    
        public virtual ICollection<MRBRoom> MRBRooms { get; set; }
    }
}
