//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingManifestReturnedItem
    {
        public string ID { get; set; }
        public string ItemName { get; set; }
        public string ItemDes { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Order { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
    }
}
