//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingManifest
    {
        public PackingManifest()
        {
            this.PackingManifestDetails = new HashSet<PackingManifestDetail>();
        }
    
        public string ID { get; set; }
        public string OrderCode { get; set; }
        public string CustomerPO { get; set; }
        public string PONo { get; set; }
        public string InvoiceNo { get; set; }
        public string Description { get; set; }
        public int CreatorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> isConfirm { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string AttachmentLink { get; set; }
        public string TEMP1 { get; set; }
        public string TEMP2 { get; set; }
        public string TEMP3 { get; set; }
        public Nullable<int> isCoordinate { get; set; }
        public string CustomerCode { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<PackingManifestDetail> PackingManifestDetails { get; set; }
    }
}
