//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStockFromERP
    {
        public string CustomerPO { get; set; }
        public string POItem { get; set; }
        public string SizeName { get; set; }
        public string ColorName { get; set; }
        public string CombName { get; set; }
        public Nullable<int> TotalContainerStockIn { get; set; }
        public Nullable<int> TotalQuantityStockIn { get; set; }
        public Nullable<int> TotalContainerStockOut { get; set; }
        public Nullable<int> TotalQuantityStockOur { get; set; }
        public Nullable<int> OrderState { get; set; }
        public Nullable<int> CompleteState { get; set; }
        public string ID { get; set; }
    }
}
