//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAConfigure
    {
        public string ReasonID { get; set; }
        public System.Guid PositionID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
    
        public virtual UserPosition UserPosition { get; set; }
        public virtual SAReason SAReason { get; set; }
    }
}
