//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShelfInformation
    {
        public string ComputerID { get; set; }
        public string Factory { get; set; }
        public string ShelfID { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
