//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteFunction_UserGroup
    {
        public int GroupFunctionID { get; set; }
        public int UserGroup { get; set; }
        public int SiteFunctionID { get; set; }
        public Nullable<short> Enabled { get; set; }
    
        public virtual UserGroup UserGroup1 { get; set; }
        public virtual SiteFunction SiteFunction { get; set; }
    }
}
