//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteFunction
    {
        public SiteFunction()
        {
            this.SiteFunction_UserGroup = new HashSet<SiteFunction_UserGroup>();
        }
    
        public int SiteFunctionID { get; set; }
        public string SiteFunctionName { get; set; }
        public string SiteFunctionNameEN { get; set; }
        public string SiteFunctionNameCN { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string URL { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<short> Enabled { get; set; }
        public string IconCssClass { get; set; }
    
        public virtual ICollection<SiteFunction_UserGroup> SiteFunction_UserGroup { get; set; }
    }
}
