//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInEquipment
    {
        public StockInEquipment()
        {
            this.StockInEquipmentDetails = new HashSet<StockInEquipmentDetail>();
            this.StockInEquipmentDetails1 = new HashSet<StockInEquipmentDetail>();
            this.StockInEquipmentDetails2 = new HashSet<StockInEquipmentDetail>();
        }
    
        public string ID { get; set; }
        public string OrderCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Temp1 { get; set; }
        public string Temp2 { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<StockInEquipmentDetail> StockInEquipmentDetails { get; set; }
        public virtual ICollection<StockInEquipmentDetail> StockInEquipmentDetails1 { get; set; }
        public virtual ICollection<StockInEquipmentDetail> StockInEquipmentDetails2 { get; set; }
    }
}
