//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInEquipmentDetail
    {
        public string ID { get; set; }
        public string StockInEquipmentID { get; set; }
        public string ItemID { get; set; }
        public string ItemDetailID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UnitID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Description { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual Item Item2 { get; set; }
        public virtual ItemDetail ItemDetail { get; set; }
        public virtual ItemDetail ItemDetail1 { get; set; }
        public virtual ItemDetail ItemDetail2 { get; set; }
        public virtual StockInEquipment StockInEquipment { get; set; }
        public virtual StockInEquipment StockInEquipment1 { get; set; }
        public virtual StockInEquipment StockInEquipment2 { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual Unit Unit2 { get; set; }
    }
}
