//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_account
    {
        public string userID { get; set; }
        public string user_pss { get; set; }
        public string userName { get; set; }
        public string EnglishName { get; set; }
        public string user_sex { get; set; }
        public string user_position { get; set; }
        public string user_group { get; set; }
        public Nullable<int> departmentID { get; set; }
        public string user_mail { get; set; }
        public Nullable<int> user_phone { get; set; }
        public Nullable<System.DateTime> user_create_pss_date { get; set; }
        public Nullable<System.DateTime> user_expired_pss_date { get; set; }
        public Nullable<System.DateTime> user_start_date { get; set; }
        public Nullable<int> user_status { get; set; }
        public Nullable<int> typeID { get; set; }
    }
}
