//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.SiteFunction_UserGroup = new HashSet<SiteFunction_UserGroup>();
            this.Users = new HashSet<User>();
        }
    
        public int UserGroupID { get; set; }
        public string UserGroupName { get; set; }
        public Nullable<short> Enabled { get; set; }
        public Nullable<int> isAdmin { get; set; }
    
        public virtual ICollection<SiteFunction_UserGroup> SiteFunction_UserGroup { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
