//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetOrderFromERP
    {
        public string OrderID { get; set; }
        public string SampleTypeID { get; set; }
        public string OrderType { get; set; }
        public string FEPOCode { get; set; }
        public int MachineType { get; set; }
        public string OrderDate { get; set; }
        public string CompleteDate { get; set; }
        public string CompanyStyleCode { get; set; }
        public string OriginalStyle { get; set; }
        public string StyleName { get; set; }
        public string CustomerStyleCode { get; set; }
        public string CustomerID { get; set; }
        public string FactoryID { get; set; }
        public string StyleSeasonID { get; set; }
        public int MachineYear { get; set; }
        public string MachineRequire { get; set; }
        public string DealPerson { get; set; }
        public string ColorGroupID { get; set; }
        public decimal Price { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string Remark { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string CreateUserID { get; set; }
        public string CreateDate { get; set; }
        public string LastUpdateUserID { get; set; }
        public string LastUpdateDate { get; set; }
        public string PointOn { get; set; }
        public string Status { get; set; }
        public string StandardSizeName { get; set; }
        public int SizeTableType { get; set; }
        public string StyleTypeID { get; set; }
        public string DeliveryCountryID { get; set; }
        public string CompanyID { get; set; }
        public string ProfitCenterCode { get; set; }
        public string OrderCustomerPO { get; set; }
        public string FinalCustomerPO { get; set; }
        public string OrderCustomerID { get; set; }
        public string InvoiceCustomerID { get; set; }
        public string PayCustomerID { get; set; }
        public string DeliveryCustomerID { get; set; }
        public string FEStyleCode { get; set; }
        public string OrderTypeID { get; set; }
        public string TPOrderCode { get; set; }
        public string QuoteOrderCode { get; set; }
        public string HistoryOrderCode { get; set; }
        public Nullable<bool> SalesApproved { get; set; }
        public Nullable<bool> SalesOrderApproved { get; set; }
        public int OrderStatus { get; set; }
        public string QuotaTypeID { get; set; }
        public string Distination { get; set; }
        public Nullable<decimal> QuotaQuantity { get; set; }
        public string TransportTypeID { get; set; }
        public Nullable<decimal> YDMax { get; set; }
        public Nullable<decimal> YDMin { get; set; }
        public int TradeType { get; set; }
        public string PaymentTermCode { get; set; }
        public string AgreementContent { get; set; }
        public string BusinessGroupID { get; set; }
        public string HandbookCode { get; set; }
        public bool IsSuit { get; set; }
        public bool IsSend { get; set; }
        public string TaxID { get; set; }
        public string TradeID { get; set; }
        public Nullable<int> OrderState { get; set; }
        public string CloseDate { get; set; }
        public Nullable<int> StyleYear { get; set; }
        public string CloseUserID { get; set; }
        public Nullable<int> IsInventory { get; set; }
        public string OperateUserID { get; set; }
        public string SexTypeID { get; set; }
        public string LengthTypeID { get; set; }
        public string StyleType_tID { get; set; }
        public Nullable<int> completeState { get; set; }
        public string CompleteDateTime { get; set; }
        public string CompleteUserID { get; set; }
        public Nullable<int> AccessoryPurchaseState { get; set; }
        public Nullable<int> FabricPurchaseState { get; set; }
        public Nullable<decimal> ConvertRate { get; set; }
        public string SizeGroupID { get; set; }
        public string IntendingOrderID { get; set; }
        public string ParentOrderID { get; set; }
        public string isNote { get; set; }
        public string ReceivablesDesi { get; set; }
        public string BuyMsg { get; set; }
        public string InvoiceCustomerIDForTP { get; set; }
        public string GarmentContractNum { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> BillingState { get; set; }
        public string BillingCloseDate { get; set; }
        public string StrategyType { get; set; }
        public string Picture { get; set; }
        public Nullable<decimal> CommissionRate { get; set; }
        public string IsPP { get; set; }
        public string IsQRS { get; set; }
        public string IsKeyStyle { get; set; }
        public string AGPOrderType { get; set; }
        public Nullable<short> StatusAllowClosedByMR { get; set; }
        public string StatusAllowClosedByMRDate { get; set; }
        public Nullable<short> StatusAllowClosedByPRO { get; set; }
        public string StatusAllowClosedByPRODate { get; set; }
        public Nullable<int> isAllowCancelClose { get; set; }
        public string RequestCodeCancelClose { get; set; }
    }
}
