//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFDocumentType
    {
        public WFDocumentType()
        {
            this.WFMains = new HashSet<WFMain>();
            this.WFNodes = new HashSet<WFNode>();
            this.WFDelegates = new HashSet<WFDelegate>();
        }
    
        public string DocumentTypeID { get; set; }
        public string DocumentTypeName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public string Parameter { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public string Temp3 { get; set; }
    
        public virtual ICollection<WFMain> WFMains { get; set; }
        public virtual ICollection<WFNode> WFNodes { get; set; }
        public virtual ICollection<WFDelegate> WFDelegates { get; set; }
    }
}
