//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFMainDetail
    {
        public WFMainDetail()
        {
            this.WFRefferences = new HashSet<WFRefference>();
        }
    
        public string MainDetailID { get; set; }
        public string MainID { get; set; }
        public string NodeID { get; set; }
        public string DelegateID { get; set; }
        public Nullable<int> PostUserID { get; set; }
        public Nullable<int> CheckUserID { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> isFinished { get; set; }
        public string Comment { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public string Temp3 { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual WFMain WFMain { get; set; }
        public virtual WFNode WFNode { get; set; }
        public virtual ICollection<WFRefference> WFRefferences { get; set; }
    }
}
