//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFMain
    {
        public WFMain()
        {
            this.WFMainDetails = new HashSet<WFMainDetail>();
        }
    
        public string MainID { get; set; }
        public string OrderCode { get; set; }
        public string DocumentTypeID { get; set; }
        public Nullable<int> isFinished { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public string Temp3 { get; set; }
    
        public virtual User User { get; set; }
        public virtual WFDocumentType WFDocumentType { get; set; }
        public virtual ICollection<WFMainDetail> WFMainDetails { get; set; }
    }
}
