//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFNodeDetail
    {
        public string NodeDetailID { get; set; }
        public string NodeID { get; set; }
        public Nullable<int> CostCenterCode { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public string DelegateID { get; set; }
        public Nullable<int> isDelegate { get; set; }
        public string Condition { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual CostCenter CostCenter { get; set; }
        public virtual User User { get; set; }
        public virtual WFNode WFNode { get; set; }
    }
}
