//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFNode
    {
        public WFNode()
        {
            this.WFMainDetails = new HashSet<WFMainDetail>();
            this.WFNodeDetails = new HashSet<WFNodeDetail>();
        }
    
        public string NodeID { get; set; }
        public string DocumentTypeID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> Status { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public string Temp3 { get; set; }
    
        public virtual WFDocumentType WFDocumentType { get; set; }
        public virtual ICollection<WFMainDetail> WFMainDetails { get; set; }
        public virtual ICollection<WFNodeDetail> WFNodeDetails { get; set; }
    }
}
