//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFRefference
    {
        public WFRefference()
        {
            this.WFRefferenceDetails = new HashSet<WFRefferenceDetail>();
        }
    
        public string ID { get; set; }
        public string MainDetailID { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> SenderID { get; set; }
        public string SenderName { get; set; }
        public string RefferenceList { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public string Temp3 { get; set; }
    
        public virtual User User { get; set; }
        public virtual WFMainDetail WFMainDetail { get; set; }
        public virtual ICollection<WFRefferenceDetail> WFRefferenceDetails { get; set; }
    }
}
