//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHExportOrder
    {
        public WHExportOrder()
        {
            this.WHExportOrderDetails = new HashSet<WHExportOrderDetail>();
        }
    
        public string ID { get; set; }
        public string OrderCode { get; set; }
        public string CustomerPO { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> isConfirm { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public string Temp3 { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<WHExportOrderDetail> WHExportOrderDetails { get; set; }
    }
}
