//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHImportOrder
    {
        public WHImportOrder()
        {
            this.WHImportOrderDetails = new HashSet<WHImportOrderDetail>();
        }
    
        public string ID { get; set; }
        public string OrderCode { get; set; }
        public string CustomerPO { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<int> Status { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public string Temp3 { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<WHImportOrderDetail> WHImportOrderDetails { get; set; }
    }
}
