//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEA_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHImportOrderDetail
    {
        public string ID { get; set; }
        public string WHImportOrderID { get; set; }
        public string PackingManifestDetailID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public string Temp3 { get; set; }
        public string ShelfID { get; set; }
    
        public virtual WHImportOrder WHImportOrder { get; set; }
        public virtual PackingManifestDetail PackingManifestDetail { get; set; }
        public virtual ItemDetail ItemDetail { get; set; }
    }
}
